# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resh < Formula
  desc "Context-based replacement for zsh and bash shell history"
  homepage "https://github.com/quanchuen/resh"
  version "4.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.0/resh_4.0.0_darwin_amd64.tar.gz"
      sha256 "df5170cc0771c8f48e42632fabc3ee832b58f4cbec30ee930420bc93969e0273"

      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.0/resh_4.0.0_darwin_arm64.tar.gz"
      sha256 "f51485b1f4acd08a97c351af7e6c906a92758de1a0d8cd318afecc2c0ccd133f"

      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.0/resh_4.0.0_linux_amd64.tar.gz"
      sha256 "96fccb7f7991beb53e650e82f7a57f5862be65b068d260bddd690392ee3d871b"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.0/resh_4.0.0_linux_armv6.tar.gz"
      sha256 "7f89fb25213dc2aa518250cb2ebb433568b1a35a6190277887bbf98a2d6b9783"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.0/resh_4.0.0_linux_arm64.tar.gz"
      sha256 "051779dcb7cfabb41e40d46092b7104dfeea577d19087d54b2fecc8f11ac5175"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
  end

  def caveats
    <<~EOS
      To finish the installation run:
        resh-setup

      This installs RESH into ~/.resh and adds it to your ~/.zshrc and ~/.bashrc.
      Run resh-setup again after every `brew upgrade resh`.
      Use `brew upgrade resh` instead of `reshctl update`.

      To uninstall run `brew uninstall resh && rm -rf ~/.resh`
      and remove the RESH lines from ~/.zshrc and ~/.bashrc.
    EOS
  end

  test do
    system libexec/"bin/resh-control", "--help"
  end
end
