# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resh < Formula
  desc "Context-based replacement for zsh and bash shell history"
  homepage "https://github.com/quanchuen/resh"
  version "4.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.1/resh_4.0.1_darwin_amd64.tar.gz"
      sha256 "49b4fcf1b9a50eb0794fd48671347f2d88e2e87a3a7f95d1d6434c14a3c977f8"

      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.1/resh_4.0.1_darwin_arm64.tar.gz"
      sha256 "9d59b31e024af8be59fefa40ac44c31b1ae001b512e1887cc906e42b09169774"

      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.1/resh_4.0.1_linux_amd64.tar.gz"
      sha256 "8a4398cd832bfd77aa51f9dbed08015cb0c7b2c20012c26ba60939a7b14018b9"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.1/resh_4.0.1_linux_armv6.tar.gz"
      sha256 "e6360f4e331c65faf968d08e4c60608a55d4f2cffac964d51fb7809fd58a3e4e"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quanchuen/resh/releases/download/v4.0.1/resh_4.0.1_linux_arm64.tar.gz"
      sha256 "ef392090dbf700436bf86aaaf8438cf2478fce5c4b93209c0032877fe952d402"
      define_method(:install) do
        libexec.install Dir["*"]
        (bin/"resh-setup").write <<~EOS
          #!/bin/bash
          cd "#{libexec}" && exec scripts/install.sh "$@"
        EOS
        chmod 0755, bin/"resh-setup"
      end
    end
  end

  def caveats
    <<~EOS
      To finish the installation run:
        resh-setup

      This installs RESH into ~/.resh and adds it to your ~/.zshrc and ~/.bashrc.
      Run resh-setup again after every `brew upgrade resh`.
      Use `brew upgrade resh` instead of `reshctl update`.

      To uninstall run `brew uninstall resh && rm -rf ~/.resh`
      and remove the RESH lines from ~/.zshrc and ~/.bashrc.
    EOS
  end

  test do
    system libexec/"bin/resh-control", "--help"
  end
end
